name: Movies
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  #rxDart
  rxdart: ^0.18.0

  #http
  http: ^0.12.0

  #Toast
  toast: ^0.1.5

  #flutter pagination Helper
  flutter_pagination_helper: ^1.0.1+2

  flutter_paginator: ^0.0.6




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
